<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?= $this->title ?></title>
		<link href="<?= Zend_Registry::get('baseURL') ?>/styles/site.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?= Zend_Registry::get('baseURL') ?>/scripts/jquery-1.4.1.min.js"></script>
		<script type="text/javascript" src="<?= Zend_Registry::get('baseURL') ?>/scripts/calendar.js"></script>
	</head>
	<body>
		<div id="wrapper">
			<div id="top"></div>
			<?php
				if(Zend_Auth::getInstance()->hasIdentity()){
					$role = Zend_Auth::getInstance()->getIdentity()->role;
				}
				else{
					$role = 'none';
				}
			?>
			<?php if($role !== 'none'): ?>
				<div id="top-logout">
					<a href="<?= Zend_Registry::get('baseURL') ?>/auth/logout">Log out</a>
					<div class="clear"></div>
				</div>
			<?php endif; ?>
			<?php if($role == 'admin' || $role == 'superadmin'): ?>
				<div id="menu">
					<?php
						$request = Zend_Controller_Front::getInstance()->getRequest();
						$controller = $request->getControllerName();
					?>
					<ul>
						<li><a href="<?= Zend_Registry::get('baseURL') ?>/" <?= ($controller=="index"?' class="active"':'') ?>>Appointments</a></li>
						<li><a href="<?= Zend_Registry::get('baseURL') ?>/beosztas" <?= ($controller=="beosztas"?' class="active"':'') ?>>Schedule</a></li>
						<?php if($role == 'superadmin'): ?>
							<li><a href="<?= Zend_Registry::get('baseURL') ?>/felhasznalok" <?= ($controller=="felhasznalok"?' class="active"':'') ?>>Users</a></li>
						<?php endif; ?>
					</ul>
					<div class="clear"></div>
				</div>
			<?php endif; ?>
			<div id="content">
				<?= $this->layout()->content; ?>
			</div>
		</div>
	</body>
</html>
